title: Default Page

columns:
  main:
    width: 1/2
    fields:
      defaultHeadline:
        label:
          nl: Error pagina
          en: Error page
          fr: Erreur page
        type: headline
      defaultSmiley:
        label:
          nl: Error smiley
          en: Error smiley
          fr: Erreur smiley
        type: text
        maxlength: 8
        placeholder: :(
        help:
          nl: bv. "**:(**" - Leeg laten voor weg te laten.
          en: fe. "**:(**" - Leave empty for no smiley.
          fr: pe. "**:(**" - Vide pour laisser de côté.
      defaultTitle:
        label:
          nl: Error titel
          en: Error title
          fr: Erreur titre
        type: text
        maxlength: 32
        required: true
      defaultParagraph:
        label:
          nl: Error tekst
          en: Error text
          fr: Erreur texte
        type: writer
        inline: true
        maxlength: 80
        required: true
      defaultButton:
        label:
          nl: Error knop
          en: Error button
          fr: Erreur bouton
        extends: fields/buttons
        required: true
        max: 1