title: Project page

columns:
  left:
    width: 1/3
    fields:
      projectNameHeadline:
        label: When creating a project
        type: headline
        numbered: false
      info:
        label: Info
        type: info
        text: |
          [Placeholder] Here comes some info on how to manage projects...
      peopleWithAccessHeadline:
        label: People with access
        type: headline
        numbered: false
      peopleWithAccessInfo:
        label: Warning
        type: info
        theme: notice
        text: Here comes text
      peopleWithAccess:
        label: People
        type: users
        # query: kirby.users.filterBy("role", "client")
  
  main:
    width: 2/3
    fields:
      projectContentHeadline:
        label: Project content
        type: headline
      projectTitle:
        label: Title
        type: text
        maxlength: 48
        required: true
        placeholder: "{{ page.title }}"
        help: The name of the clients company
      projectDescription:
        label: Description
        type: writer
        inline: true
        maxlength: 320
        required: true
        help: Short description of the proposition. What will our people make?
      line-a:
        type: line
      
      assignedEmployeesHeadline:
        label: Assigned Employees
        type: headline
      assignedEmployees:
        label: Assigned employees
        type: pages
        query: site.index.filterBy('template', 'in', ['employee'])
        layout: cards
        help: Select the people that would work on this project
        required: true
        image:
          query: page.profilePicture.toFile
          cover: true