title: Site

tabs:
  cvKit:
    label:
      nl: CV kit
      en: CV kit
      fr: CV kit
    icon: page

    columns:
      left:
        width: 1/3
        fields:
          cvKitHeadline:
            label: Upthrust CV Kit
            type: headline
            numbered: false
          cvKitInfo:
            label: Info
            type: info
            text: |
              [Placeholder] Here comes some info on how to use the CV kit...
      right:
        width: 2/3
        fields:
          logoHeadline:
            label:
              nl: Bedrijfsinformatie
              en: Company info
              fr: Informations sur l'entreprise
            type: headline
          logo:
            label: Logo
            type: files
            layout: cards
            max: 1
            required: true
            width: 1/3
            help:
              nl: Gebruik een **.svg** bestand indien mogelijk
              en: Use a **.svg** file if possible
              fr: utilisez un fichier **.svg** si possible
          companyDescription:
            label:
              nl: Beschrijving
              en: Description
              fr: Description
            type: writer
            inline: true
            max: 180
            width: 2/3
            required: true
            help:
              nl: Beschrijf de diensten van je bedrijf in **1-2 zinnen**
              en: Describe your company's services in **1-2 sentences**
              fr: Décrivez les services de votre entreprise en **1-2 phrases**
          line-a:
            type: line
          contactHeadline:
            label: Contact
            type: headline
          contactInfo:
            label:
              nl: Contact info
              en: Contact info
              fr: Informations de contact
            type: object
            width: 1/2
            fields:
              name:
                label:
                  nl: Bedrijfsnaam
                  en: Company name
                  fr: Nom de l'entreprise
                type: text
                required: true
              phoneNumber:
                label:
                  nl: Telefoonnummer
                  en: Phone number
                  fr: Numéro de téléphone
                type: tel
                required: true
              email:
                label: Email
                type: email
                required: true
              website:
                label:
                  nl: Website
                  en: Website
                  fr: Site web
                type: url
                required: true
          socials:
            extends: fields/socials
          line-b:
            type: line
          ctaHeadline:
            label: CTA
            type: headline
            width: 1/2
          ctaGap:
            type: gap
            width: 1/4
          ctaDisplayToggle:
            extends: fields/toggle
            label:
            default: true
            text:
              -
                  nl: "Verbergen"
                  en: "Hide"
                  fr: "Cacher"
              -
                  nl: "Weergeven"
                  en: "Display"
                  fr: "Affichage"
          ctaTitleDefault:
            label:
              nl: Titel (standaard kleur)
              en: Title (standard color)
              fr: Titre (couleur standard)
            type: text
            maxlength: 64
            when:
              ctaDisplayToggle: true
          ctaTitleColor:
            label:
              nl: Titel (merkkleur)
              en: Title (brand color)
              fr: Titre (couleur de marque)
            type: text
            maxlength: 64
            when:
              ctaDisplayToggle: true
          ctaButtons:
            label:
              nl: Knoppen
              en: Buttons
              fr: Boutons
            extends: fields/buttons
            when:
              ctaDisplayToggle: true
            
  employees:
    label:
      nl: Werknemers
      en: Employees
      fr: Employés
    icon: user

    columns:
      left:
        width: 1/3
        fields:
          employeesHeadline:
            label:
              nl: Werknemers
              en: Employees
              fr: Employés
            type: headline
            numbered: false
          employeesInfo:
            label: Attention
            type: info
            text: |
              [Placeholder] Here comes some info on adding new employees...
      right:
        width: 2/3
        sections:
          employeesDrafts:
            label: Drafts
            type: pages
            status: draft
            templates: employee
            layout: cardlets
            image:
              query: page.profilePicture.toFile()
              cover: true
          publishedEmployees:
            type: fields
            fields:
              employeesPublished:
                label:
                  nl: Werknemers
                  en: Employees
                  fr: Employés
                type: pages
                status: listed
                templates: employee
                layout: cardlets
                image:
                  query: page.profilePicture.toFile()
                  cover: true
            
  teams:
    label:
      nl: Afdelingen
      en: Departments
      fr: Départements
    icon: users

    columns:
      left:
        width: 1/3
        fields:
          departmentsHeadline:
            label:
              nl: Afdelingen
              en: Departments
              fr: Départements
            type: headline
            numbered: false
          departmentsInfo:
            label: Info
            type: info
            text: |
              [Placeholder] Here comes some info on how to manage departments...
      right:
        width: 2/3
        fields:
          departments:
            label:
              nl: Afdelingen
              en: Departments
              fr: Départements
            type: structure
            columns:
              name:
                width: 1/4
              employees:
                width: 3/4
            fields:
              name:
                label:
                  nl: Naam
                  en: Name
                  fr: Nom
                type: text
                maxlength: 32
                required: true
              employees:
                label:
                  nl: Werknemers
                  en: Employees
                  fr: Employés
                type: pages
                query: site.index.filterBy('template', 'in', ['employee'])
                limit: 6
                layout: cardlets
                image:
                  query: page.profilePicture.toFile
                  cover: true
  
  projects:
    label:
      nl: Projecten
      en: Projects
      fr: Projets
    icon: folder

    columns:
      left:
        width: 1/3
        fields:
          projectsHeadline:
            label:
              nl: Projecten
              en: Projects
              fr: Projets
            type: headline
            numbered: false
          projectsInfo:
            label: Info
            type: info
            text: |
              [Placeholder] Here comes some info on how to manage projects...

      right:
        width: 2/3
        sections:
          projectsDrafts:
            label: Drafts
            type: pages
            status: draft
            templates: project

          projectsPublished:
            label:
              nl: Projecten
              en: Projects
              fr: Projets
            type: pages
            status: listed
            templates: project
            layout: cardlets
            image:
              query: page.profilePicture.toFile()
              cover: true